package com.fbee.modules.mybatis.dao;

import com.fbee.modules.core.persistence.CrudDao;
import com.fbee.modules.core.persistence.annotation.MyBatisDao;
import com.fbee.modules.mybatis.entity.MembersInfoEntity;
import com.fbee.modules.mybatis.model.MembersInfo;
import com.fbee.modules.mybatis.model.MembersInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@MyBatisDao
public interface MembersInfoMapper extends CrudDao<MembersInfoEntity> {
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members_info
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	int countByExample(MembersInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members_info
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	int deleteByExample(MembersInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members_info
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members_info
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	int insert(MembersInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members_info
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	int insertSelective(MembersInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members_info
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	List<MembersInfo> selectByExample(MembersInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members_info
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	MembersInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members_info
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	int updateByExampleSelective(@Param("record") MembersInfo record, @Param("example") MembersInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members_info
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	int updateByExample(@Param("record") MembersInfo record, @Param("example") MembersInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members_info
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	int updateByPrimaryKeySelective(MembersInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members_info
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	int updateByPrimaryKey(MembersInfo record);

	/**
	 * @author xiehuig更新客户信息
	 */
	int updateMemberByCity(MembersInfo record);
	/**
	 * 根据号码获取会员信息
	 * 
	 */
	MembersInfo getByMobile(String mobile);
	MembersInfo getByOpenid(String openid);
	
	/**
	 * 注册新会�?
	 */
	Integer insertMember(MembersInfoEntity membersInfoEntity);
	
}