package com.fbee.modules.mybatis.dao;

import java.util.List;
import java.util.Map;

import com.fbee.modules.core.persistence.CrudDao;
import com.fbee.modules.core.persistence.annotation.MyBatisDao;
import com.fbee.modules.mybatis.entity.OrdersEntity;
import com.fbee.modules.mybatis.model.Orders;
import com.fbee.modules.mybatis.model.OrdersExample;
import org.apache.ibatis.annotations.Param;

@MyBatisDao
public interface OrdersMapper extends CrudDao<OrdersEntity> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Wed Mar 01 14:54:06 CST 2017
	 */
	int countByExample(OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Wed Mar 01 14:54:06 CST 2017
	 */
	int deleteByExample(OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Wed Mar 01 14:54:06 CST 2017
	 */
	int deleteByPrimaryKey(String orderNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Wed Mar 01 14:54:06 CST 2017
	 */
	int insert(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Wed Mar 01 14:54:06 CST 2017
	 */
	int insertSelective(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Wed Mar 01 14:54:06 CST 2017
	 */
	List<Orders> selectByExample(OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Wed Mar 01 14:54:06 CST 2017
	 */
	Orders selectByPrimaryKey(String orderNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Wed Mar 01 14:54:06 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Orders record, @Param("example") OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Wed Mar 01 14:54:06 CST 2017
	 */
	int updateByExample(@Param("record") Orders record, @Param("example") OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Wed Mar 01 14:54:06 CST 2017
	 */
	int updateByPrimaryKeySelective(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Wed Mar 01 14:54:06 CST 2017
	 */
	int updateByPrimaryKey(Orders record);

	/**
	 * 查询订单数量
	 * 
	 * @param map
	 * @return
	 */
	Integer getOrdersCount(Map<String, Object> map);

	/**
	 * 获取订单列表
	 * 
	 * @param map
	 * @return
	 */
	List<Orders> getOrdersList(Map<String, Object> map);

	/**
	 * 订单详情
	 * 
	 * @param orderNo
	 * @return
	 */
	Map<String, Object> getOrder(String orderNo);
	/**
	 * 取消订单
	 * @return
	 */
	int cancelOrder(Map<String, Object> map);
	
	/**
	 * 修改订单状态
	 */
	void updateStatus(Map<String, Object> map);

	/**
	 * 通用修改订单状态
	 */
	void updateCommonStatus(Map<String, Object> map);

    List<OrdersEntity> getOrdersWithStaffList(Map<String, Object> map);

    OrdersEntity getWithStaffByNo(String orderNo);
}