package com.fbee.modules.mybatis.dao;

import com.fbee.modules.core.persistence.annotation.MyBatisDao;
import com.fbee.modules.mybatis.model.OrderShareInfo;
import com.fbee.modules.mybatis.model.OrderShareInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@MyBatisDao
public interface OrderShareInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_share_info
     *
     * @mbggenerated Wed Mar 01 10:14:58 CST 2017
     */
    int countByExample(OrderShareInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_share_info
     *
     * @mbggenerated Wed Mar 01 10:14:58 CST 2017
     */
    int deleteByExample(OrderShareInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_share_info
     *
     * @mbggenerated Wed Mar 01 10:14:58 CST 2017
     */
    int deleteByPrimaryKey(String orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_share_info
     *
     * @mbggenerated Wed Mar 01 10:14:58 CST 2017
     */
    int insert(OrderShareInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_share_info
     *
     * @mbggenerated Wed Mar 01 10:14:58 CST 2017
     */
    int insertSelective(OrderShareInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_share_info
     *
     * @mbggenerated Wed Mar 01 10:14:58 CST 2017
     */
    List<OrderShareInfo> selectByExample(OrderShareInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_share_info
     *
     * @mbggenerated Wed Mar 01 10:14:58 CST 2017
     */
    OrderShareInfo selectByPrimaryKey(String orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_share_info
     *
     * @mbggenerated Wed Mar 01 10:14:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") OrderShareInfo record, @Param("example") OrderShareInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_share_info
     *
     * @mbggenerated Wed Mar 01 10:14:58 CST 2017
     */
    int updateByExample(@Param("record") OrderShareInfo record, @Param("example") OrderShareInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_share_info
     *
     * @mbggenerated Wed Mar 01 10:14:58 CST 2017
     */
    int updateByPrimaryKeySelective(OrderShareInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_share_info
     *
     * @mbggenerated Wed Mar 01 10:14:58 CST 2017
     */
    int updateByPrimaryKey(OrderShareInfo record);
}