package com.fbee.modules.mybatis.dao;

import com.fbee.modules.core.persistence.annotation.MyBatisDao;
import com.fbee.modules.mybatis.model.TenantsApplication;
import com.fbee.modules.mybatis.model.TenantsApplicationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface TenantsApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_application
     *
     * @mbggenerated Mon Mar 27 09:29:34 CST 2017
     */
    int countByExample(TenantsApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_application
     *
     * @mbggenerated Mon Mar 27 09:29:34 CST 2017
     */
    int deleteByExample(TenantsApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_application
     *
     * @mbggenerated Mon Mar 27 09:29:34 CST 2017
     */
    int deleteByPrimaryKey(Integer applicationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_application
     *
     * @mbggenerated Mon Mar 27 09:29:34 CST 2017
     */
    int insert(TenantsApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_application
     *
     * @mbggenerated Mon Mar 27 09:29:34 CST 2017
     */
    int insertSelective(TenantsApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_application
     *
     * @mbggenerated Mon Mar 27 09:29:34 CST 2017
     */
    List<TenantsApplication> selectByExample(TenantsApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_application
     *
     * @mbggenerated Mon Mar 27 09:29:34 CST 2017
     */
    TenantsApplication selectByPrimaryKey(Integer applicationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_application
     *
     * @mbggenerated Mon Mar 27 09:29:34 CST 2017
     */
    int updateByExampleSelective(@Param("record") TenantsApplication record, @Param("example") TenantsApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_application
     *
     * @mbggenerated Mon Mar 27 09:29:34 CST 2017
     */
    int updateByExample(@Param("record") TenantsApplication record, @Param("example") TenantsApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_application
     *
     * @mbggenerated Mon Mar 27 09:29:34 CST 2017
     */
    int updateByPrimaryKeySelective(TenantsApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_application
     *
     * @mbggenerated Mon Mar 27 09:29:34 CST 2017
     */
    int updateByPrimaryKey(TenantsApplication record);
}