package com.fbee.modules.mybatis.dao;

import com.fbee.modules.core.persistence.annotation.MyBatisDao;
import com.fbee.modules.mybatis.model.TenantsFunds;
import com.fbee.modules.mybatis.model.TenantsFundsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface TenantsFundsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_funds
     *
     * @mbggenerated Fri Feb 24 16:29:37 CST 2017
     */
    int countByExample(TenantsFundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_funds
     *
     * @mbggenerated Fri Feb 24 16:29:37 CST 2017
     */
    int deleteByExample(TenantsFundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_funds
     *
     * @mbggenerated Fri Feb 24 16:29:37 CST 2017
     */
    int deleteByPrimaryKey(Integer tenantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_funds
     *
     * @mbggenerated Fri Feb 24 16:29:37 CST 2017
     */
    int insert(TenantsFunds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_funds
     *
     * @mbggenerated Fri Feb 24 16:29:37 CST 2017
     */
    int insertSelective(TenantsFunds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_funds
     *
     * @mbggenerated Fri Feb 24 16:29:37 CST 2017
     */
    List<TenantsFunds> selectByExample(TenantsFundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_funds
     *
     * @mbggenerated Fri Feb 24 16:29:37 CST 2017
     */
    TenantsFunds selectByPrimaryKey(Integer tenantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_funds
     *
     * @mbggenerated Fri Feb 24 16:29:37 CST 2017
     */
    int updateByExampleSelective(@Param("record") TenantsFunds record, @Param("example") TenantsFundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_funds
     *
     * @mbggenerated Fri Feb 24 16:29:37 CST 2017
     */
    int updateByExample(@Param("record") TenantsFunds record, @Param("example") TenantsFundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_funds
     *
     * @mbggenerated Fri Feb 24 16:29:37 CST 2017
     */
    int updateByPrimaryKeySelective(TenantsFunds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_funds
     *
     * @mbggenerated Fri Feb 24 16:29:37 CST 2017
     */
    int updateByPrimaryKey(TenantsFunds record);
}