package com.fbee.modules.mybatis.dao;

import com.fbee.modules.core.persistence.CrudDao;
import com.fbee.modules.core.persistence.annotation.MyBatisDao;
import com.fbee.modules.mybatis.entity.TenantsAppsEntity;
import com.fbee.modules.mybatis.model.TenantsApps;
import com.fbee.modules.mybatis.model.TenantsAppsExample;
import java.util.List;

import com.fbee.modules.mybatis.model.TenantsSnapshotInfo;
import org.apache.ibatis.annotations.Param;

@MyBatisDao
public interface TenantsAppsMapper extends CrudDao<TenantsAppsEntity>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_apps
	 * @mbggenerated  Tue Mar 21 17:42:46 CST 2017
	 */
	int countByExample(TenantsAppsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_apps
	 * @mbggenerated  Tue Mar 21 17:42:46 CST 2017
	 */
	int deleteByExample(TenantsAppsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_apps
	 * @mbggenerated  Tue Mar 21 17:42:46 CST 2017
	 */
	int deleteByPrimaryKey(Integer tenantId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_apps
	 * @mbggenerated  Tue Mar 21 17:42:46 CST 2017
	 */
	int insert(TenantsApps record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_apps
	 * @mbggenerated  Tue Mar 21 17:42:46 CST 2017
	 */
	int insertSelective(TenantsApps record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_apps
	 * @mbggenerated  Tue Mar 21 17:42:46 CST 2017
	 */
	List<TenantsApps> selectByExample(TenantsAppsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_apps
	 * @mbggenerated  Tue Mar 21 17:42:46 CST 2017
	 */
	TenantsApps selectByPrimaryKey(Integer tenantId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_apps
	 * @mbggenerated  Tue Mar 21 17:42:46 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TenantsApps record, @Param("example") TenantsAppsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_apps
	 * @mbggenerated  Tue Mar 21 17:42:46 CST 2017
	 */
	int updateByExample(@Param("record") TenantsApps record, @Param("example") TenantsAppsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_apps
	 * @mbggenerated  Tue Mar 21 17:42:46 CST 2017
	 */
	int updateByPrimaryKeySelective(TenantsApps record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_apps
	 * @mbggenerated  Tue Mar 21 17:42:46 CST 2017
	 */
	int updateByPrimaryKey(TenantsApps record);

	/**
	 * 获取站点名称
	 * @param tenantId
	 * @return
	 */
	String getWebsiteName(Integer tenantId);
	
	/**
	 * 通过二级域名获取租户id
	 */
	Integer getTenantIdByDomain(String domain);
	
	/**
	 * 通过ID获取租户二级域名
	 */
	String getDomainByTenantId(String id);

	String getlogopath(String domain);

	TenantsSnapshotInfo getSnapshotById(String id);
}