package com.fbee.modules.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class TenantsApps implements Serializable{
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_apps.TENANT_ID
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	private Integer tenantId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_apps.WEBSITE_NAME
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	private String websiteName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_apps.CONTACT_ADDRESS
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	private String contactAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_apps.REGISTER_PHONE
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	private String registerPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_apps.CONTACT_PHONE
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	private String contactPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_apps.DOMAIN
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	private String domain;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_apps.WEBSITE_URL
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	private String websiteUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_apps.WEBSITE_CONSOLE_URL
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	private String websiteConsoleUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_apps.WEBSITE_LOGO
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	private String websiteLogo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_apps.DUE_DATE
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	private Date dueDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_apps.is_usable
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	private String isUsable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_apps.add_time
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_apps.add_account
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	private String addAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_apps.modify_time
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	private Date modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_apps.modify_account
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	private String modifyAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_apps.privince
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	private String privince;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_apps.city
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_apps.area
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	private String area;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_apps.TENANT_STATUS
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	private String tenantStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_apps.SALES_PERSON
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	private String salesPerson;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_apps.remarks
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_apps.TENANT_CODE
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	private String tenantCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_apps.apply_time
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	private Date applyTime;


	private String tenantsPhone;

	public String getTenantsPhone() {
		return tenantsPhone;
	}

	public void setTenantsPhone(String tenantsPhone) {
		this.tenantsPhone = tenantsPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_apps.TENANT_ID
	 * @return  the value of tenants_apps.TENANT_ID
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public Integer getTenantId() {
		return tenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_apps.TENANT_ID
	 * @param tenantId  the value for tenants_apps.TENANT_ID
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public void setTenantId(Integer tenantId) {
		this.tenantId = tenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_apps.WEBSITE_NAME
	 * @return  the value of tenants_apps.WEBSITE_NAME
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public String getWebsiteName() {
		return websiteName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_apps.WEBSITE_NAME
	 * @param websiteName  the value for tenants_apps.WEBSITE_NAME
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public void setWebsiteName(String websiteName) {
		this.websiteName = websiteName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_apps.CONTACT_ADDRESS
	 * @return  the value of tenants_apps.CONTACT_ADDRESS
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public String getContactAddress() {
		return contactAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_apps.CONTACT_ADDRESS
	 * @param contactAddress  the value for tenants_apps.CONTACT_ADDRESS
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public void setContactAddress(String contactAddress) {
		this.contactAddress = contactAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_apps.REGISTER_PHONE
	 * @return  the value of tenants_apps.REGISTER_PHONE
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public String getRegisterPhone() {
		return registerPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_apps.REGISTER_PHONE
	 * @param registerPhone  the value for tenants_apps.REGISTER_PHONE
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public void setRegisterPhone(String registerPhone) {
		this.registerPhone = registerPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_apps.CONTACT_PHONE
	 * @return  the value of tenants_apps.CONTACT_PHONE
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public String getContactPhone() {
		return contactPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_apps.CONTACT_PHONE
	 * @param contactPhone  the value for tenants_apps.CONTACT_PHONE
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_apps.DOMAIN
	 * @return  the value of tenants_apps.DOMAIN
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public String getDomain() {
		return domain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_apps.DOMAIN
	 * @param domain  the value for tenants_apps.DOMAIN
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public void setDomain(String domain) {
		this.domain = domain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_apps.WEBSITE_URL
	 * @return  the value of tenants_apps.WEBSITE_URL
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public String getWebsiteUrl() {
		return websiteUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_apps.WEBSITE_URL
	 * @param websiteUrl  the value for tenants_apps.WEBSITE_URL
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public void setWebsiteUrl(String websiteUrl) {
		this.websiteUrl = websiteUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_apps.WEBSITE_CONSOLE_URL
	 * @return  the value of tenants_apps.WEBSITE_CONSOLE_URL
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public String getWebsiteConsoleUrl() {
		return websiteConsoleUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_apps.WEBSITE_CONSOLE_URL
	 * @param websiteConsoleUrl  the value for tenants_apps.WEBSITE_CONSOLE_URL
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public void setWebsiteConsoleUrl(String websiteConsoleUrl) {
		this.websiteConsoleUrl = websiteConsoleUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_apps.WEBSITE_LOGO
	 * @return  the value of tenants_apps.WEBSITE_LOGO
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public String getWebsiteLogo() {
		return websiteLogo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_apps.WEBSITE_LOGO
	 * @param websiteLogo  the value for tenants_apps.WEBSITE_LOGO
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public void setWebsiteLogo(String websiteLogo) {
		this.websiteLogo = websiteLogo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_apps.DUE_DATE
	 * @return  the value of tenants_apps.DUE_DATE
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public Date getDueDate() {
		return dueDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_apps.DUE_DATE
	 * @param dueDate  the value for tenants_apps.DUE_DATE
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_apps.is_usable
	 * @return  the value of tenants_apps.is_usable
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public String getIsUsable() {
		return isUsable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_apps.is_usable
	 * @param isUsable  the value for tenants_apps.is_usable
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public void setIsUsable(String isUsable) {
		this.isUsable = isUsable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_apps.add_time
	 * @return  the value of tenants_apps.add_time
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_apps.add_time
	 * @param addTime  the value for tenants_apps.add_time
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_apps.add_account
	 * @return  the value of tenants_apps.add_account
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public String getAddAccount() {
		return addAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_apps.add_account
	 * @param addAccount  the value for tenants_apps.add_account
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public void setAddAccount(String addAccount) {
		this.addAccount = addAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_apps.modify_time
	 * @return  the value of tenants_apps.modify_time
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_apps.modify_time
	 * @param modifyTime  the value for tenants_apps.modify_time
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_apps.modify_account
	 * @return  the value of tenants_apps.modify_account
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public String getModifyAccount() {
		return modifyAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_apps.modify_account
	 * @param modifyAccount  the value for tenants_apps.modify_account
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public void setModifyAccount(String modifyAccount) {
		this.modifyAccount = modifyAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_apps.privince
	 * @return  the value of tenants_apps.privince
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public String getPrivince() {
		return privince;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_apps.privince
	 * @param privince  the value for tenants_apps.privince
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public void setPrivince(String privince) {
		this.privince = privince;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_apps.city
	 * @return  the value of tenants_apps.city
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_apps.city
	 * @param city  the value for tenants_apps.city
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_apps.area
	 * @return  the value of tenants_apps.area
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public String getArea() {
		return area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_apps.area
	 * @param area  the value for tenants_apps.area
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public void setArea(String area) {
		this.area = area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_apps.TENANT_STATUS
	 * @return  the value of tenants_apps.TENANT_STATUS
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public String getTenantStatus() {
		return tenantStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_apps.TENANT_STATUS
	 * @param tenantStatus  the value for tenants_apps.TENANT_STATUS
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public void setTenantStatus(String tenantStatus) {
		this.tenantStatus = tenantStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_apps.SALES_PERSON
	 * @return  the value of tenants_apps.SALES_PERSON
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public String getSalesPerson() {
		return salesPerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_apps.SALES_PERSON
	 * @param salesPerson  the value for tenants_apps.SALES_PERSON
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public void setSalesPerson(String salesPerson) {
		this.salesPerson = salesPerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_apps.remarks
	 * @return  the value of tenants_apps.remarks
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_apps.remarks
	 * @param remarks  the value for tenants_apps.remarks
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_apps.TENANT_CODE
	 * @return  the value of tenants_apps.TENANT_CODE
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public String getTenantCode() {
		return tenantCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_apps.TENANT_CODE
	 * @param tenantCode  the value for tenants_apps.TENANT_CODE
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public void setTenantCode(String tenantCode) {
		this.tenantCode = tenantCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_apps.apply_time
	 * @return  the value of tenants_apps.apply_time
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public Date getApplyTime() {
		return applyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_apps.apply_time
	 * @param applyTime  the value for tenants_apps.apply_time
	 * @mbggenerated  Tue Mar 21 17:42:45 CST 2017
	 */
	public void setApplyTime(Date applyTime) {
		this.applyTime = applyTime;
	}

	private static final long serialVersionUID = 1L;
}