package com.fbee.modules.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class TradeRecords {
    /**
     * 表：trade_records
     * 字段：TRADE_FLOW_NO
     * 注释：支付流水号
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.TRADE_FLOW_NO
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    private String tradeFlowNo;

    /**
     * 表：trade_records
     * 字段：TRADE_TYPE
     * 注释：支付类型 01充值 02提现 03退款
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.TRADE_TYPE
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    private String tradeType;

    /**
     * 表：trade_records
     * 字段：TRADE_AMOUNT
     * 注释：支付金额
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.TRADE_AMOUNT
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    private BigDecimal tradeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.COUNTER_FEE
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    private BigDecimal counterFee;

    /**
     * 表：trade_records
     * 字段：TRADE_TIME
     * 注释：支付时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.TRADE_TIME
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    private Date tradeTime;

    /**
     * 表：trade_records
     * 字段：TRADE_STATIS
     * 注释：支付状态 01处理中 02支付成功 03支付失败
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.TRADE_STATIS
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    private String tradeStatis;

    /**
     * 表：trade_records
     * 字段：INITIATOR_TYPE
     * 注释：发起方类型 01客户 02租户
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.INITIATOR_TYPE
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    private String initiatorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.FAILURE_MSG
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    private String failureMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.TRADE_RESULT_CODE
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    private String tradeResultCode;

    /**
     * 表：trade_records
     * 字段：is_usable
     * 注释：
     *
     * @mbggenerated
     */
    private String isUsable;

    /**
     * 表：trade_records
     * 字段：add_account
     * 注释：添加人
     *
     * @mbggenerated
     */
    private String addAccount;

    /**
     * 表：trade_records
     * 字段：add_time
     * 注释：添加时间
     *
     * @mbggenerated
     */
    private Date addTime;



    /**
     * 表：trade_records
     * 字段：modify_time
     * 注释：修改时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.modify_account
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    private String modifyAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.modify_time
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.REQUEST_RESULT
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    private String requestResult;

    /**
     * 表：trade_records
     * 字段：ORDER_NO
     * 注释：订单号
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.ORDER_NO
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.OUT_ORDER_NO
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    private String outOrderNo;

    /**
     * 表：trade_records
     * 字段：TRADE_CHANNEL
     * 注释：支付渠道 01支付宝 02微信扫码 03微信公众号
     *
     * @mbggenerated
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.TRADE_CHANNEL
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    private String tradeChannel;

    /**
     * 表：trade_records
     * 字段：TRADE_CHANNEL_NO
     * 注释：支付渠道流水号
     *
     * @mbggenerated
     */
    private String tradeChannelNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.TRADE_FLOW_NO
     *
     * @return the value of trade_records.TRADE_FLOW_NO
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    public String getTradeFlowNo() {
        return tradeFlowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.TRADE_FLOW_NO
     *
     * @param tradeFlowNo the value for trade_records.TRADE_FLOW_NO
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    public void setTradeFlowNo(String tradeFlowNo) {
        this.tradeFlowNo = tradeFlowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.TRADE_TYPE
     *
     * @return the value of trade_records.TRADE_TYPE
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.TRADE_TYPE
     *
     * @param tradeType the value for trade_records.TRADE_TYPE
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.TRADE_AMOUNT
     *
     * @return the value of trade_records.TRADE_AMOUNT
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    public BigDecimal getTradeAmount() {
        return tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.TRADE_AMOUNT
     *
     * @param tradeAmount the value for trade_records.TRADE_AMOUNT
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    public void setTradeAmount(BigDecimal tradeAmount) {
        this.tradeAmount = tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.COUNTER_FEE
     *
     * @return the value of trade_records.COUNTER_FEE
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    public BigDecimal getCounterFee() {
        return counterFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.COUNTER_FEE
     *
     * @param counterFee the value for trade_records.COUNTER_FEE
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    public void setCounterFee(BigDecimal counterFee) {
        this.counterFee = counterFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.TRADE_TIME
     *
     * @return the value of trade_records.TRADE_TIME
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    public Date getTradeTime() {
        return tradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.TRADE_TIME
     *
     * @param tradeTime the value for trade_records.TRADE_TIME
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    public void setTradeTime(Date tradeTime) {
        this.tradeTime = tradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.TRADE_STATIS
     *
     * @return the value of trade_records.TRADE_STATIS
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    public String getTradeStatis() {
        return tradeStatis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.TRADE_STATIS
     *
     * @param tradeStatis the value for trade_records.TRADE_STATIS
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    public void setTradeStatis(String tradeStatis) {
        this.tradeStatis = tradeStatis == null ? null : tradeStatis.trim();
    }

    public String getInitiatorType() {
        return initiatorType;
    }

    public void setInitiatorType(String initiatorType) {
        this.initiatorType = initiatorType == null ? null : initiatorType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.FAILURE_MSG
     *
     * @return the value of trade_records.FAILURE_MSG
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    public String getFailureMsg() {
        return failureMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.FAILURE_MSG
     *
     * @param failureMsg the value for trade_records.FAILURE_MSG
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    public void setFailureMsg(String failureMsg) {
        this.failureMsg = failureMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.TRADE_RESULT_CODE
     *
     * @return the value of trade_records.TRADE_RESULT_CODE
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    public String getTradeResultCode() {
        return tradeResultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.TRADE_RESULT_CODE
     *
     * @param tradeResultCode the value for trade_records.TRADE_RESULT_CODE
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    public void setTradeResultCode(String tradeResultCode) {
        this.tradeResultCode = tradeResultCode;
    }

    public String getIsUsable() {
        return isUsable;
    }

    public void setIsUsable(String isUsable) {
        this.isUsable = isUsable == null ? null : isUsable.trim();
    }

    public String getAddAccount() {
        return addAccount;
    }

    public void setAddAccount(String addAccount) {
        this.addAccount = addAccount == null ? null : addAccount.trim();
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public String getModifyAccount() {
        return modifyAccount;
    }

    public void setModifyAccount(String modifyAccount) {
        this.modifyAccount = modifyAccount == null ? null : modifyAccount.trim();
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.modify_time
     *
     * @param modifyTime the value for trade_records.modify_time
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.REQUEST_RESULT
     *
     * @return the value of trade_records.REQUEST_RESULT
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    public String getRequestResult() {
        return requestResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.REQUEST_RESULT
     *
     * @param requestResult the value for trade_records.REQUEST_RESULT
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    public void setRequestResult(String requestResult) {
        this.requestResult = requestResult;
    }

    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.OUT_ORDER_NO
     *
     * @return the value of trade_records.OUT_ORDER_NO
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    public String getOutOrderNo() {
        return outOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.OUT_ORDER_NO
     *
     * @param outOrderNo the value for trade_records.OUT_ORDER_NO
     *
     * @mbggenerated Fri Feb 24 16:22:17 CST 2017
     */
    public void setOutOrderNo(String outOrderNo) {
        this.outOrderNo = outOrderNo;
    }

    public String getTradeChannel() {
        return tradeChannel;
    }

    public void setTradeChannel(String tradeChannel) {
        this.tradeChannel = tradeChannel == null ? null : tradeChannel.trim();
    }

    public String getTradeChannelNo() {
        return tradeChannelNo;
    }

    public void setTradeChannelNo(String tradeChannelNo) {
        this.tradeChannelNo = tradeChannelNo == null ? null : tradeChannelNo.trim();
    }
}